# Phiên bản docker-compose đang dùng
version: '3.8'

# Khai báo các container (services) sẽ chạy
services:

  # 1. Django container
  web:
    # Image đã build sẵn trên Docker Hub
    image: ntnguyen055/doctor-appointment:latest
    
    # Tên container khi chạy (dễ quản lý hơn)
    container_name: django_web
    
    # Nếu container bị crash thì tự chạy lại
    restart: always

    # Lệnh chạy khi container start
    # Gunicorn dùng để chạy Django trên production
    command: gunicorn docappsystem.wsgi:application --bind 0.0.0.0:8000

    # Chỉ mở cổng nội bộ giữa các container
    # Không public ra ngoài internet
    expose:
      - "8000"

    # Biến môi trường truyền vào container
    # Django sẽ đọc các biến này trong settings.py
    environment:

      # Tắt chế độ debug (production mode)
      - DEBUG=0

      # Thông tin AWS S3 (dùng để lưu ảnh, file upload) 
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}

      # Thông tin AWS RDS (database MySQL trên cloud) 
      - RDS_DB_NAME=${RDS_DB_NAME}        # tên database
      - RDS_USERNAME=${RDS_USERNAME}      # user database
      - RDS_PASSWORD=${RDS_PASSWORD}      # password database
      - RDS_ENDPOINT=${RDS_ENDPOINT}      # địa chỉ server RDS

      # Thông tin AWS Replica RDS (database MySQL trên cloud) 
      - RDS_REPLICA_ENDPOINT=${RDS_REPLICA_ENDPOINT}

      - RDS_PORT=3306                     # cổng MySQL (mặc định là 3306)


  # 2. Nginx container
  nginx:
    # Image nginx nhẹ (alpine = bản tối giản, chạy nhanh)
    image: nginx:alpine

    # Tên container
    container_name: nginx_proxy

    # Nếu container bị lỗi thì tự chạy lại
    restart: always

    # Map cổng 80 của máy thật -> cổng 80 của container
    # Nghĩa là truy cập trình duyệt: http://localhost
    ports:
      - "80:80"

    # Mount file config nginx từ máy thật vào container
    # Bạn chỉnh file default.conf thì nginx trong container cũng thay đổi theo
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    # Đảm bảo container nginx chỉ chạy sau khi container web đã chạy
    depends_on:
      - web