# Phiên bản docker-compose đang dùng
version: '3.8'

networks:
  devsecops_net:
    driver: bridge

# Khai báo các container (services) sẽ chạy
services:

  # 1. Django container
  web:
    # Nhận image từ Jenkins Pipeline
    image: ${DOCKER_USER}/${IMAGE_NAME}:${TAG}
    
    # Tên container khi chạy
    container_name: django_web
    
    # Nếu container bị crash thì tự chạy lại
    restart: always

    # Lệnh chạy khi container start
    command: gunicorn docappsystem.wsgi:application --bind 0.0.0.0:8000

    # Chỉ mở cổng nội bộ giữa các container
    expose:
      - "8000"
      
    networks:
      - devsecops_net

    # Biến môi trường truyền vào container
    environment:
      - DEBUG=0

      # Thông tin AWS S3 (dùng để lưu ảnh, file upload) 
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME}

      # Thông tin AWS RDS (database MySQL trên cloud) 
      - RDS_DB_NAME=${RDS_DB_NAME}        # tên database
      - RDS_USERNAME=${RDS_USERNAME}      # user database
      - RDS_PASSWORD=${RDS_PASSWORD}      # password database
      - RDS_ENDPOINT=${RDS_ENDPOINT}      # địa chỉ server RDS
      - RDS_REPLICA_ENDPOINT=${RDS_REPLICA_ENDPOINT}
      - RDS_PORT=3306                     # cổng MySQL (mặc định là 3306)

  # 2. LỚP KHIÊN BẢO VỆ (WAF ModSecurity) thay thế cho Nginx cũ
  waf:
    # Image Nginx tích hợp sẵn OWASP ModSecurity CRS
    image: owasp/modsecurity-crs:nginx
    container_name: nginx_proxy_waf
    ports:
      - "80:8080" # Bản ModSecurity CRS dùng cổng 8080 nội bộ
    environment:
      # Proxy ngược (Reverse Proxy) trỏ thẳng vào container web
      - BACKEND=http://web:8000
      - SEC_RULE_ENGINE=On
      # --- CẤU HÌNH REAL IP CHO AWS ALB ---
      - SET_REAL_IP_FROM=172.31.0.0/16,10.0.0.0/8
      - REAL_IP_HEADER=X-Forwarded-For
      # --- ÉP XUẤT FILE AUDIT LOG CHO WAZUH ---
      - MODSEC_AUDIT_ENGINE=RelevantOnly
      - MODSEC_AUDIT_LOG_FORMAT=JSON
      - MODSEC_AUDIT_LOG=/var/log/nginx/modsec_audit.log
    depends_on:
      - web
    networks:
      - devsecops_net
    volumes:
      - ./waf-logs:/var/log/nginx
    restart: always